[package]
name = "easy_savescum"
version = "0.1.0"
authors = ["Psilon <pzixel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
chrono = "0.4.11"
notify = "4.0.12"